# Generate daily report: today prediction + yesterday backtest -> daily_reports/
import json
import urllib.request
import sys
from datetime import datetime
from pathlib import Path
from collections import defaultdict

PROJECT_DIR = Path(__file__).parent.parent
RESULTS_DIR = PROJECT_DIR / "data" / "results"
REPORTS_DIR = PROJECT_DIR / "daily_reports"

STOCKS = [
    ("sh600438", "Tongwei", "Solar"),
    ("sh601012", "LONGi", "Solar"),
    ("sz300274", "Sungrow", "Solar"),
    ("sh688599", "Trina", "Solar"),
    ("sz300751", "Maxwell", "Solar"),
    ("sz002202", "Goldwind", "Wind"),
    ("sh601615", "MingYang", "Wind"),
    ("sh603606", "OrientCable", "Wind"),
    ("sz300850", "Xinqianglian", "Wind"),
    ("sz001289", "Longyuan", "Wind"),
    ("sz002230", "iFlytek", "AI"),
    ("sh688256", "Cambricon", "AI"),
    ("sz000977", "Inspur", "AI"),
    ("sz300308", "Zhongji", "AI"),
    ("sz300033", "Hithink", "AI"),
    ("sz300750", "CATL", "Energy"),
    ("sz300014", "EVE", "Energy"),
    ("sz002074", "Guoxuan", "Energy"),
    ("sz002460", "Ganfeng", "Energy"),
    ("sh601727", "SEC", "Energy"),
    ("sz002415", "Hikvision", "Vision"),
    ("sz002236", "Dahua", "Vision"),
    ("sz002920", "DesaySV", "Vision"),
    ("sz300496", "ThunderSoft", "Vision"),
    ("sh603501", "WillSemi", "Vision"),
]

RATING_EMOJI = {"Overweight": "OW", "Buy": "BUY", "Hold": "HOLD", "Underweight": "UW", "Sell": "SELL"}


def get_kline(sid):
    url = (
        "http://web.ifzq.gtimg.cn/appstock/app/fqkline/get"
        "?param={sid},day,,,5,qfq".format(sid=sid)
    )
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    resp = urllib.request.urlopen(req, timeout=10)
    return json.loads(resp.read().decode("utf-8"))["data"][sid]["qfqday"]


def load_predictions(date_str):
    preds = {}
    for f in RESULTS_DIR.glob("*_" + date_str + "_analysis.cache.json"):
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
            preds[d["symbol"]] = d
        except Exception:
            pass
    return preds


def pct_str(v):
    return "{:+.2f}%".format(v)


# ---- discover dates ----
today = datetime.now()
today_str = today.strftime("%Y-%m-%d")

all_dates = set()
for f in RESULTS_DIR.glob("*_analysis.cache.json"):
    try:
        d = json.loads(f.read_text(encoding="utf-8"))
        td = d.get("trade_date", "")
        if td:
            all_dates.add(td)
    except Exception:
        pass

sorted_dates = sorted(all_dates)
if len(sorted_dates) < 1:
    print("No analysis data")
    sys.exit(0)

analysis_date = sorted_dates[-1]
backtest_date = sorted_dates[-2] if len(sorted_dates) >= 2 else None

print("Today: " + today_str)
print("Analysis date: " + analysis_date)
print("Backtest date: " + str(backtest_date))

# ---- build report ----
lines = []
lines.append("# DayTradeSelfOptAgent Daily Report - " + today_str)
lines.append("")
lines.append(
    "> **Disclaimer**: This report is auto-generated by an AI multi-agent system. "
    "All analysis results are for educational/research purposes ONLY and do NOT constitute "
    "any investment advice. Past performance does not guarantee future results. "
    "The system may produce errors - do NOT use for real trading."
)
lines.append("")
lines.append("**Generated**: " + today.strftime("%Y-%m-%d %H:%M"))
lines.append("**Strategy**: One-Day Swing (Day0 analyze -> Day1 buy -> Day2 force close)")
lines.append("**Model**: DeepSeek-V4  temperature=0.1")
lines.append("**Target**: >=1% gain (net ~0.89% after 0.11% cost)")
lines.append("")

# ====== Part 1: Today's Prediction ======
lines.append("---")
lines.append("")
lines.append("## 1. Today's Prediction (" + analysis_date + " -> next trading day)")
lines.append("")

preds = load_predictions(analysis_date)
if preds:
    by_sector = defaultdict(list)
    for sid, name, sector in STOCKS:
        code = sid[2:]
        if code in preds:
            by_sector[sector].append((code, name, preds[code]))

    buy_count = sum(1 for p in preds.values() if p["rating"] in ("Buy", "Overweight"))
    hold_count = sum(1 for p in preds.values() if p["rating"] == "Hold")
    uw_count = sum(1 for p in preds.values() if p["rating"] == "Underweight")
    sell_count = sum(1 for p in preds.values() if p["rating"] == "Sell")

    lines.append("| BUY/OW | HOLD | UW | SELL |")
    lines.append("|:--:|:--:|:--:|:--:|")
    lines.append(
        "| **{b}** | {h} | {u} | {s} |".format(
            b=buy_count, h=hold_count, u=uw_count, s=sell_count
        )
    )
    lines.append("")

    sector_names = [("Solar", "Solar"), ("Wind", "Wind"), ("AI", "AI"),
                    ("Energy", "Energy Storage"), ("Vision", "Vision")]
    for sector_key, sector_label in sector_names:
        if sector_key not in by_sector:
            continue
        lines.append("### " + sector_label)
        lines.append("")
        lines.append("| Code | Name | Rating | Confidence |")
        lines.append("|------|------|:--:|:--:|")
        for code, name, p in by_sector[sector_key]:
            r = p["rating"]
            lines.append(
                "| {c} | {n} | {rt} | {cf:.0%} |".format(
                    c=code, n=name, rt=r, cf=p["confidence"]
                )
            )
        lines.append("")

    if buy_count > 0:
        lines.append("### Buy Signals")
        lines.append("")
        for p in preds.values():
            if p["rating"] in ("Buy", "Overweight"):
                summary = (p.get("summary") or p.get("investment_logic") or "-")[:200]
                lines.append(
                    "- **{s}** ({r}, conf {cf:.0%}): {sm}".format(
                        s=p["symbol"], r=p["rating"], cf=p["confidence"], sm=summary
                    )
                )
        lines.append("")
else:
    lines.append("*No analysis data for today*")
    lines.append("")

# ====== Part 2: Yesterday's Backtest ======
lines.append("---")
lines.append("")
lines.append(
    "## 2. Yesterday's Backtest (" + str(backtest_date) + " prediction -> next-day actual)"
)
lines.append("")

if backtest_date:
    backtest_preds = load_predictions(backtest_date)
    if backtest_preds:
        hit = 0
        avoid = 0
        miss = 0
        step = 0
        table_lines = []
        table_lines.append(
            "| Code | Name | Sector | Prediction | Conf | CloseChg | OpenBuy | Result |"
        )
        table_lines.append(
            "|------|------|--------|:--:|:--:|:--:|:--:|:--:|"
        )

        for sid, name, sector in STOCKS:
            code = sid[2:]
            bp = backtest_preds.get(code)
            if not bp:
                continue
            try:
                klines = get_kline(sid)
                d0 = None
                d1 = None
                for k in klines:
                    if k[0] == backtest_date:
                        d0 = float(k[2])
                    if k[0] > backtest_date and d1 is None:
                        d1 = {"open": float(k[1]), "close": float(k[2])}
                if d0 is None or d1 is None:
                    continue
            except Exception:
                continue

            close_pct = (d1["close"] / d0 - 1) * 100
            open_pct = (d1["close"] / d1["open"] - 1) * 100
            should_buy = bp["rating"] in ("Buy", "Overweight")
            actually_up = close_pct >= 1.0

            if should_buy and actually_up:
                v = "HIT"
            elif should_buy:
                v = "MISS"
            elif actually_up:
                v = "STEP"
            else:
                v = "AVOID"

            if should_buy and actually_up:
                hit += 1
            elif should_buy:
                miss += 1
            elif actually_up:
                step += 1
            else:
                avoid += 1

            table_lines.append(
                "| {c} | {n} | {sec} | {r} | {cf:.0%} | {cp} | {op} | {v} |".format(
                    c=code,
                    n=name,
                    sec=sector,
                    r=bp["rating"],
                    cf=bp["confidence"],
                    cp=pct_str(close_pct),
                    op=pct_str(open_pct),
                    v=v,
                )
            )

        total = hit + avoid + miss + step
        lines.append("| Metric | Value |")
        lines.append("|--------|:--:|")
        lines.append("| Total | {t} |".format(t=total))
        lines.append("| HIT (Buy->up>=1%) | {h} |".format(h=hit))
        lines.append("| AVOID (Hold->not up) | {a} |".format(a=avoid))
        lines.append("| MISS (Buy->down/fail) | {m} |".format(m=miss))
        lines.append("| STEP (Hold->up>=1%) | {s} |".format(s=step))
        lines.append(
            "| Accuracy | **{acc:.0f}%** |".format(acc=(hit + avoid) / total * 100)
        )
        if hit + miss > 0:
            lines.append(
                "| Buy Precision | {h}/{t2} = {pct:.0f}% |".format(
                    h=hit, t2=hit + miss, pct=hit / (hit + miss) * 100
                )
            )
        lines.append("")

        lines.extend(table_lines)
        lines.append("")
    else:
        lines.append("*No prediction data for " + str(backtest_date) + "*")
else:
    lines.append("*No backtest data available (need >=2 days of analysis cache)*")

# ---- write ----
REPORTS_DIR.mkdir(exist_ok=True)
report_path = REPORTS_DIR / (today_str + "_daily_report.md")
report_path.write_text("\n".join(lines), encoding="utf-8")
print("\nReport saved: " + str(report_path))
